version: "3.8"

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - api

  api:
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"

volumes:
  static_volume: