name: Test

on:
  pull_request:
    branches:
      - '*'
    types: [opened, reopened, synchronize]


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - run: pip install -r requirements.txt

    - name: Run dockerized tests
      run: cd api && python manage.py test
